selftest/membarrier: fix build error
hulk inclusion
category: bugzilla
bugzilla: 28332
CVE: NA

-------------------------------------------------

commit 2293e84612ef ("selftests, sched/membarrier: Add multi-threaded test")
add a new test for membarrier. Some non-existent functions were used.

ksft_set_plan() was introduced by the following commit :
	5821ba969511 ("selftests: Add test plan API to kselftest.h and adjust callers")
which was not be merged.

so we get the next error when compile this testcase :
	membarrier_test_single_thread.c: In function 'main':
	membarrier_test_single_thread.c:15:2: warning: implicit declaration of function 'ksft_set_plan'; did you mean 'ksft_exit_pass'? [-Wimplicit-function-declaration]
	  ksft_set_plan(13);
	  ^~~~~~~~~~~~~
	  ksft_exit_pass

Fixes :  2293e84612ef ("selftests, sched/membarrier: Add multi-threaded test")
Signed-off-by: Cheng Jian <cj.chengjian@huawei.com>
Reviewed-By: Xie XiuQi <xiexiuqi@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>